# deploy/compose.trainerapi.web_app.yml

services:
  tapi_app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: tapi_app:${VERSION_TAG:-latest}
    container_name: tapi_app
    env_file: ../.env
    ports:
      - "51000:51000"
    volumes:
      - /beahea_prod/app/logs:/app/logs
    networks:
      tapi_dev_network:
        ipv4_address: 172.18.0.33
    restart: unless-stopped
    command: >
      sh -c "alembic -c /app/alembic.ini upgrade head && 
      gunicorn run:app -c /app/gunicorn.conf.py"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8666/api/info/health" ]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  tapi_dev_network:
    external: True